# Autogenerated wrapper script for hyperfine_jll for aarch64-apple-darwin
export hyperfine

JLLWrappers.@generate_wrapper_header("hyperfine")
JLLWrappers.@declare_executable_product(hyperfine)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        hyperfine,
        "bin/hyperfine",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
