# Autogenerated wrapper script for hyperfine_jll for i686-linux-musl
export hyperfine

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("hyperfine")
JLLWrappers.@declare_executable_product(hyperfine)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        hyperfine,
        "bin/hyperfine",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
