# Autogenerated wrapper script for hyperfine_jll for x86_64-w64-mingw32
export hyperfine

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("hyperfine")
JLLWrappers.@declare_executable_product(hyperfine)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_executable_product(
        hyperfine,
        "bin\\hyperfine.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
